# my scripts
SCRIPTS_PATH="/Users/pedroduarte/dev/scripts"
#programs
alias daily="$SCRIPTS_PATH/programs/daily.sh"
alias jira="$SCRIPTS_PATH/programs/jira.sh"
alias gmail="$SCRIPTS_PATH/programs/gmail.sh"
alias duo="$SCRIPTS_PATH/programs/duo.sh"
#libs
alias end="$SCRIPTS_PATH/libs/end.sh"
alias pr="$SCRIPTS_PATH/libs/pr.sh"
alias studio="$SCRIPTS_PATH/libs/studio.sh"
alias co="$SCRIPTS_PATH/libs/nest.sh"
alias help="$SCRIPTS_PATH/help.sh"
alias h="$SCRIPTS_PATH/help.sh"
alias display="$SCRIPTS_PATH/display.sh"
alias insta="$SCRIPTS_PATH/insta.sh"
alias meet="$SCRIPTS_PATH/meet.sh"
alias nextjs="$SCRIPTS_PATH/nextjs.sh"
alias vs="$SCRIPTS_PATH/vs.sh"
alias calendar="$SCRIPTS_PATH/calendar.sh"
alias drive="$SCRIPTS_PATH/drive.sh"
alias translate="$SCRIPTS_PATH/translate.sh"
alias github="$SCRIPTS_PATH/github.sh"
alias slack="$SCRIPTS_PATH/slack.sh"
alias whats="$SCRIPTS_PATH/whats.sh"
alias gather="$SCRIPTS_PATH/gather.sh"
alias close="$SCRIPTS_PATH/close.sh"
alias endgame="$SCRIPTS_PATH/endgame.sh"
alias figma="$SCRIPTS_PATH/figma.sh"
alias up="$SCRIPTS_PATH/update.sh"
# git commands
alias dev="$SCRIPTS_PATH/git-commands/dev.sh"
alias main="$SCRIPTS_PATH/git-commands/main.sh"
alias update="$SCRIPTS_PATH/git-commands/update.sh"
# pnpm aliases
alias i="pnpm i"
alias b="pnpm build"
alias build="pnpm build"
alias clean="pnpm run clean"
alias lint="pnpm run lint"
alias audit="pnpm run audit"
alias tc="pnpm typecheck"
alias typecheck="pnpm run typecheck"
alias test="pnpm test"
alias t="pnpm test"
alias tw="pnpm test:watch"
alias e2e="pnpm e2e"
alias go="pnpm run go"
alias ib="i && b"
alias ibd="i && b && pnpm dev"
# git aliases
alias pull="git pull"
alias push="git push"
alias status="git status"
#git hub aliases
alias browse="gh browse"
## my projects
# stark
alias arya="$SCRIPTS_PATH/projects/stark/arya.sh"
alias bran="$SCRIPTS_PATH/projects/stark/bran.sh"
alias sansa="$SCRIPTS_PATH/projects/stark/sansa.sh"
# rohan
alias dunharrow="$SCRIPTS_PATH/projects/dunharrow.sh"
alias edoras="$SCRIPTS_PATH/projects/edoras.sh"
alias westfold="$SCRIPTS_PATH/projects/westfold.sh"
# yavanna
alias laurelin="$SCRIPTS_PATH/projects/laurelin.sh"
alias telperion="$SCRIPTS_PATH/projects/telperion.sh"
#aule
alias angainor="$SCRIPTS_PATH/projects/angainor.sh"
alias naugrim="$SCRIPTS_PATH/projects/naugrim.sh"
# qc projects
PROJECTS_QC_PATH="$SCRIPTS_PATH/projects/qc"
alias rkratos="$PROJECTS_QC_PATH/reset_kratos.sh"
alias atreus="$PROJECTS_QC_PATH/atreus.sh"
alias bord="$PROJECTS_QC_PATH/bord.sh"
alias niamh="$PROJECTS_QC_PATH/niamh.sh"
alias skaldic="$PROJECTS_QC_PATH/skaldic.sh"
alias skaldicn="$PROJECTS_QC_PATH/skaldic_next.sh"
alias skaldic-next="$PROJECTS_QC_PATH/skaldic_next.sh"
alias sleipnir="$PROJECTS_QC_PATH/sleipnir.sh"
alias fenrir="$PROJECTS_QC_PATH/fenrir.sh"
## odin
alias odin="$PROJECTS_QC_PATH/odin/odin.sh"
alias odinb="$PROJECTS_QC_PATH/odin/odinb.sh"
alias odinf="$PROJECTS_QC_PATH/odin/odinf.sh"
# libs
alias data="$SCRIPTS_PATH/libs/data_pull.sh"
